config/routes.rb
Rails.application.routes.draw do

  resources :broadcasts
  devise_for :super_admins
  devise_for :customer_admins, :controllers => {
    sessions: 'customer_admins/sessions',
    confirmations:  'customer_admins/confirmations',
    passwords:  'customer_admins/passwords',
    unlocks: 'customer_admins/unlocks'
  }

  devise_for :admins

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  root to: "posts#index"

  resources :posts
  resources :articles
  resources :media_items
  resources :events

  get '/theme/', to: 'theme#edit'
  patch "/theme" => "theme#update"

  get '/bio/', to: 'bio#edit'
  patch "/bio" => "bio#update"

  get '/customer_settings/', to: 'customer_settings#edit'
  patch "/customer_settings" => "customer_settings#update"

  get '/broadcast/', to: 'broadcasts#new'

  namespace :api do
    namespace :v1 do
      resources :post, only: [:index, :show], controller: "posts"
      resources :bio, only: [:index], controller: "bios"
      resources :calendar, only: [:index], controller: "calendar"
      resources :media, only: [:index, :show], controller: "media"
      resources :theme, only: [:index], controller: "theme"
      resources :user, only: [:create, :show, :update], controller: "app_users"
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/app_user.rb
class AppUser < ApplicationRecord
  belongs_to :customer
end

app/models/bio.rb
class Bio < ApplicationRecord
  belongs_to :customer
  has_many :career_items
  mount_uploader :photo, BioPhotoUploader
end

app/models/broadcast.rb
require 'houston'

class Broadcast < ApplicationRecord
  belongs_to :customer

  def send_push(users)
    customer = self.customer
    if !customer.present?
      return
    end
    if customer.ios_push_cert == nil
      return
    end
    users.each do |user|
      if user.push_token == nil
        next
      end
      apn = Houston::Client.development
      apn.certificate = customer.ios_push_cert
      notification = Houston::Notification.new(device: user.push_token)
      notification.alert = self.title
      notification.custom_data = {
        title: self.title,
        content: self.body,
        message_id: "900"
      }
      puts apn
      apn.push(notification)
    end
  end
end

app/models/career_item.rb
class CareerItem < ApplicationRecord
  belongs_to :bio
end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :posts
  has_many :media_items
  has_many :events

  after_initialize :generate_api_key, if: :new_record?

  def generate_api_key
    self.api_key = ::SecureRandom.uuid
  end

end

app/models/customer_admin.rb
class CustomerAdmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/customer_setting.rb
class CustomerSetting < ApplicationRecord
end

app/models/event.rb
require 'carrierwave/orm/activerecord'
class Event < ApplicationRecord
  belongs_to :customer
  mount_uploader :image, EventImageUploader
end

app/models/media_item.rb
require 'carrierwave/orm/activerecord'
class MediaItem < ApplicationRecord
  belongs_to :customer
  mount_uploader :image, MediaItemImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer

  mount_uploader :header_image, PostImageUploader
  mount_uploader :icon_image, PostIconImageUploader

end

app/models/super_admin.rb
class SuperAdmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/theme.rb
class Theme < ApplicationRecord
  belongs_to :customer
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bio_helper.rb
module BioHelper
end

app/helpers/broadcasts_helper.rb
module BroadcastsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/theme_helper.rb
module ThemeHelper
end

app/views/layouts/application.html.haml
= render 'partials/header'
= render 'partials/nav_bar'
#wrapper
  #sidebar-wrapper
    %ul.sidebar-nav
      %li
        %a#posts_menu_item{:href => posts_path} Posts
      %li
        %a#media_menu_item{:href => media_items_path} Media
      %li
        %a#bio_menu_item{:href => "/bio"} Bio
      %li
        %a#broadcast_menu_item{:href => "/broadcast"} Broadcast
      %li
        %a#calendar_menu_item{:href => events_path} Calendar
      %li
        %a#theme_menu_item{:href => "/theme"} Theme
      %li
        %a#customer_settings_menu_item{:href => "/customer_settings"} Customer Settings
  #page-content-wrapper
    .container-fluid
      = yield
:javascript
  $("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#wrapper").toggleClass("toggled");
    $("#toggle_button").toggleClass("toggled");
  });
  (function(h,o,t,j,a,r){
      h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
      h._hjSettings={hjid:494315,hjsv:5};
      a=o.getElementsByTagName('head')[0];
      r=o.createElement('script');r.async=1;
      r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
      a.appendChild(r);
  })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');

app/views/layouts/login.html.haml
= render 'partials/header'
#login_page
  .darken
    = yield

app/views/layouts/mobile.html.haml
= render 'partials/header'
= render 'partials/nav_bar'
= yield

app/views/partials/_header.html.haml
!!! 5
%html
  %head
    %title RFBase
    = csrf_meta_tags
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body

app/views/partials/_nav_bar.html.haml
#navbar.navbar-collapse
  .navbar-header
    %a.navbar-brand{:href => "#"}
      = image_tag "car_logo.png", style:"width:220px"
  %ul.nav.navbar-nav.navbar-right.hmenu
    - if customer_admin_signed_in?
      %li= "#{current_customer_admin.first_name} #{current_customer_admin.last_name}"
      %li.divider
      %li= link_to('Log Out', destroy_customer_admin_session_path, :method => :delete, :type => 'button', :class => 'logout')
    - else
      %li= link_to('Login', new_customer_admin_session_path)