config/routes.rb
Rails.application.routes.draw do

  resources :broadcasts
  devise_for :super_admins
  devise_for :customer_admins, :controllers => {
    sessions: 'customer_admins/sessions',
    confirmations:  'customer_admins/confirmations',
    passwords:  'customer_admins/passwords',
    unlocks: 'customer_admins/unlocks'
  }

  devise_for :admins

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  root to: "posts#index"

  resources :posts
  resources :articles
  resources :media_items
  resources :events

  get '/theme/', to: 'theme#edit'
  patch "/theme" => "theme#update"

  get '/bio/', to: 'bio#edit'
  patch "/bio" => "bio#update"

  get '/customer_settings/', to: 'customer_settings#edit'
  patch "/customer_settings" => "customer_settings#update"

  get '/broadcast/', to: 'broadcasts#new'

  namespace :api do
    namespace :v1 do
      resources :post, only: [:index, :show], controller: "posts"
      resources :bio, only: [:index], controller: "bios"
      resources :calendar, only: [:index], controller: "calendar"
      resources :media, only: [:index, :show], controller: "media"
      resources :theme, only: [:index], controller: "theme"
      resources :user, only: [:create, :show, :update], controller: "app_users"
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/app_user.rb
class AppUser < ApplicationRecord
  belongs_to :customer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bio.rb
class Bio < ApplicationRecord
  belongs_to :customer
  has_many :career_items
  mount_uploader :photo, BioPhotoUploader
end

app/models/broadcast.rb
require 'houston'

class Broadcast < ApplicationRecord
  belongs_to :customer

  def send_push(users)
    customer = self.customer
    if !customer.present?
      return
    end
    if customer.ios_push_cert == nil
      return
    end
    users.each do |user|
      if user.push_token == nil
        next
      end
      apn = Houston::Client.development
      apn.certificate = customer.ios_push_cert
      notification = Houston::Notification.new(device: user.push_token)
      notification.alert = self.title
      notification.custom_data = {
        title: self.title,
        content: self.body,
        message_id: "900"
      }
      puts apn
      apn.push(notification)
    end
  end
end

app/models/career_item.rb
class CareerItem < ApplicationRecord
  belongs_to :bio
end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :posts
  has_many :media_items
  has_many :events

  after_initialize :generate_api_key, if: :new_record?

  def generate_api_key
    self.api_key = ::SecureRandom.uuid
  end

end

app/models/customer_admin.rb
class CustomerAdmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/customer_setting.rb
class CustomerSetting < ApplicationRecord
end

app/models/event.rb
require 'carrierwave/orm/activerecord'
class Event < ApplicationRecord
  belongs_to :customer
  mount_uploader :image, EventImageUploader
end

app/models/media_item.rb
require 'carrierwave/orm/activerecord'
class MediaItem < ApplicationRecord
  belongs_to :customer
  mount_uploader :image, MediaItemImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer

  mount_uploader :header_image, PostImageUploader
  mount_uploader :icon_image, PostIconImageUploader

end

app/models/super_admin.rb
class SuperAdmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/theme.rb
class Theme < ApplicationRecord
  belongs_to :customer
end

app/controllers/bio_controller.rb
class BioController < ApplicationController
  before_action :current_customer
  before_action :find_bio, only: [:show, :edit, :update, :delete]

  def show
  end

  def edit
  end

  def update
    if @bio.update_attributes(bio_params)
      flash[:success] = "Successfully updated bio!"
      redirect_to '/bio'
    else
      flash[:alert] = "Error updating bio!"
      render :edit
    end
  end

  def delete
  end

  private

  def bio_params
    params.require(:bio).permit(:photo, :name, :date_of_birth, :biography, :facebook_url, :twitter_url, :instagram_url, :web_url, :photo, :lives, :bootsy_image_gallery_id)
  end

  def find_bio
    @bio = Bio.where(customer_id: current_customer.id).first
    #Every customer should have one bio
    if !@bio.present?
      puts "inside"
      @bio = Bio.new(:customer_id => current_customer.id)
      @bio.save
    end
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_customer_admin!
  before_action :current_customer

  # GET /events
  # GET /events.json
  def index
    @events = @current_customer.events.sort_by{|e| e[:date]}
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.customer = @current_customer
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:image, :caption, :date, :name)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bio_helper.rb
module BioHelper
end

app/helpers/broadcasts_helper.rb
module BroadcastsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/theme_helper.rb
module ThemeHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.file_field :image %>
    <% if f.object.image? %>
      <%= image_tag f.object.image_url %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %>
    <% end %>
    <%= f.text_field :name %>
    <%= f.text_field :caption %>
    <%= f.date_field :date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.haml
= flash_messages
#content_head
  #ch-title
    %h1 Events
  #ch-button
    %a{:href => new_event_path}
      %button.btn.btn-primary{:type => 'button'} New
.row
.col-md-12
  %table.table
    %thead.posts_head
      %tr
        %th IMAGE
        %th NAME
        %th DATE
        %th DELETE
        %th EDIT
        %th MORE
    %tbody.posts_body
      - @events.each do |event|
        %tr
          %td
            =image_tag  event.image_url, :class => "event_image"
          %td.alternate= event.name
          %td= event.date.to_s
          %td.alternate.button_cell= link_to "<span class=\"glyphicon glyphicon-trash\"></span>".html_safe, event_path(event), data: {:confirm => 'Are you sure?'}, :method => :delete
          %td.button_cell= link_to "<span class=\"glyphicon glyphicon-edit\"></span>".html_safe, edit_event_path(event)
          %td.alternate.button_cell= link_to "<span class=\"glyphicon glyphicon-plus-sign\"></span>".html_safe, event_path(event)
:javascript
  $("#calendar_menu_item").toggleClass("active")

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>