config/routes.rb
Rails.application.routes.draw do

  resources :broadcasts
  devise_for :super_admins
  devise_for :customer_admins, :controllers => {
    sessions: 'customer_admins/sessions',
    confirmations:  'customer_admins/confirmations',
    passwords:  'customer_admins/passwords',
    unlocks: 'customer_admins/unlocks'
  }

  devise_for :admins

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  root to: "posts#index"

  resources :posts
  resources :articles
  resources :media_items
  resources :events

  get '/theme/', to: 'theme#edit'
  patch "/theme" => "theme#update"

  get '/bio/', to: 'bio#edit'
  patch "/bio" => "bio#update"

  get '/customer_settings/', to: 'customer_settings#edit'
  patch "/customer_settings" => "customer_settings#update"

  get '/broadcast/', to: 'broadcasts#new'

  namespace :api do
    namespace :v1 do
      resources :post, only: [:index, :show], controller: "posts"
      resources :bio, only: [:index], controller: "bios"
      resources :calendar, only: [:index], controller: "calendar"
      resources :media, only: [:index, :show], controller: "media"
      resources :theme, only: [:index], controller: "theme"
      resources :user, only: [:create, :show, :update], controller: "app_users"
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/app_user.rb
class AppUser < ApplicationRecord
  belongs_to :customer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bio.rb
class Bio < ApplicationRecord
  belongs_to :customer
  has_many :career_items
  mount_uploader :photo, BioPhotoUploader
end

app/models/broadcast.rb
require 'houston'

class Broadcast < ApplicationRecord
  belongs_to :customer

  def send_push(users)
    customer = self.customer
    if !customer.present?
      return
    end
    if customer.ios_push_cert == nil
      return
    end
    users.each do |user|
      if user.push_token == nil
        next
      end
      apn = Houston::Client.development
      apn.certificate = customer.ios_push_cert
      notification = Houston::Notification.new(device: user.push_token)
      notification.alert = self.title
      notification.custom_data = {
        title: self.title,
        content: self.body,
        message_id: "900"
      }
      puts apn
      apn.push(notification)
    end
  end
end

app/models/career_item.rb
class CareerItem < ApplicationRecord
  belongs_to :bio
end

app/models/customer.rb
class Customer < ApplicationRecord

  has_many :posts
  has_many :media_items
  has_many :events

  after_initialize :generate_api_key, if: :new_record?

  def generate_api_key
    self.api_key = ::SecureRandom.uuid
  end

end

app/models/customer_admin.rb
class CustomerAdmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/customer_setting.rb
class CustomerSetting < ApplicationRecord
end

app/models/event.rb
require 'carrierwave/orm/activerecord'
class Event < ApplicationRecord
  belongs_to :customer
  mount_uploader :image, EventImageUploader
end

app/models/media_item.rb
require 'carrierwave/orm/activerecord'
class MediaItem < ApplicationRecord
  belongs_to :customer
  mount_uploader :image, MediaItemImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer

  mount_uploader :header_image, PostImageUploader
  mount_uploader :icon_image, PostIconImageUploader

end

app/models/super_admin.rb
class SuperAdmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/theme.rb
class Theme < ApplicationRecord
  belongs_to :customer
end

app/controllers/bio_controller.rb
class BioController < ApplicationController
  before_action :current_customer
  before_action :find_bio, only: [:show, :edit, :update, :delete]

  def show
  end

  def edit
  end

  def update
    if @bio.update_attributes(bio_params)
      flash[:success] = "Successfully updated bio!"
      redirect_to '/bio'
    else
      flash[:alert] = "Error updating bio!"
      render :edit
    end
  end

  def delete
  end

  private

  def bio_params
    params.require(:bio).permit(:photo, :name, :date_of_birth, :biography, :facebook_url, :twitter_url, :instagram_url, :web_url, :photo, :lives, :bootsy_image_gallery_id)
  end

  def find_bio
    @bio = Bio.where(customer_id: current_customer.id).first
    #Every customer should have one bio
    if !@bio.present?
      puts "inside"
      @bio = Bio.new(:customer_id => current_customer.id)
      @bio.save
    end
  end


end

app/controllers/broadcasts_controller.rb
class BroadcastsController < ApplicationController
  before_action :set_broadcast, only: [:show, :edit, :update, :destroy]
  before_action :current_customer

  # GET /broadcasts
  # GET /broadcasts.json
  def index
    @broadcasts = Broadcast.all
  end

  # GET /broadcasts/1
  # GET /broadcasts/1.json
  def show
  end

  # GET /broadcasts/new
  def new
    @broadcast = Broadcast.new
  end

  # GET /broadcasts/1/edit
  def edit
  end

  # POST /broadcasts
  # POST /broadcasts.json
  def create
    @broadcast = Broadcast.new(broadcast_params)
    @broadcast.customer = @current_customer
    users = AppUser.where(:device_type => 'ios')
    @broadcast.send_push(users)

    respond_to do |format|
      if @broadcast.save
        format.html { redirect_to '/broadcast', notice: 'Broadcast was successfully created.' }
        format.json { render :show, status: :created, location: @broadcast }
      else
        format.html { render :new }
        format.json { render json: @broadcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /broadcasts/1
  # PATCH/PUT /broadcasts/1.json
  def update
    respond_to do |format|
      if @broadcast.update(broadcast_params)
        format.html { redirect_to @broadcast, notice: 'Broadcast was successfully updated.' }
        format.json { render :show, status: :ok, location: @broadcast }
      else
        format.html { render :edit }
        format.json { render json: @broadcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /broadcasts/1
  # DELETE /broadcasts/1.json
  def destroy
    @broadcast.destroy
    respond_to do |format|
      format.html { redirect_to broadcasts_url, notice: 'Broadcast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_broadcast
      @broadcast = Broadcast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def broadcast_params
      params.require(:broadcast).permit(:title, :body, :customer_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bio_helper.rb
module BioHelper
end

app/helpers/broadcasts_helper.rb
module BroadcastsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/theme_helper.rb
module ThemeHelper
end

app/views/broadcasts/_form.html.erb
<div class="theme-form-wrapper">
  <%= simple_form_for(@broadcast) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :body %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/broadcasts/edit.html.erb
<h1>Editing Broadcast</h1>

<%= render 'form', broadcast: @broadcast %>

<%= link_to 'Show', @broadcast %> |
<%= link_to 'Back', broadcasts_path %>

app/views/broadcasts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Broadcasts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @broadcasts.each do |broadcast| %>
      <tr>
        <td><%= broadcast.title %></td>
        <td><%= broadcast.body %></td>
        <td><%= broadcast.customer %></td>
        <td><%= link_to 'Show', broadcast %></td>
        <td><%= link_to 'Edit', edit_broadcast_path(broadcast) %></td>
        <td><%= link_to 'Destroy', broadcast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Broadcast', new_broadcast_path %>

app/views/broadcasts/new.html.erb
<%= flash_messages %>
<div id="content_head">
  <h1>New Broadcast Message</h1>
</div>

<%= render 'form', broadcast: @broadcast %>

<script type="text/javascript">
  $("#broadcast_menu_item").toggleClass("active")
  function clearNotice(){
    $("#flashMessage").animate({opacity: 0}, 1500, function(){
      $("#flashMessage").toggleClass('hidden');
    });
  }
  setTimeout(clearNotice, 1000);
</script>

app/views/broadcasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @broadcast.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @broadcast.body %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @broadcast.customer %>
</p>

<%= link_to 'Edit', edit_broadcast_path(@broadcast) %> |
<%= link_to 'Back', broadcasts_path %>